import express from 'express';
import pool from './db.js';

const router = express.Router();

// --- CLASSROOMS API ---
router.get('/classrooms', async (req, res) => {
    try {
        const [rows] = await pool.execute('SELECT * FROM classrooms ORDER BY room_number ASC');
        res.json(rows);
    } catch (error) {
        console.error('Error fetching classrooms:', error);
        res.status(500).json({ error: 'Internal Server Error' });
    }
});

router.post('/classrooms', async (req, res) => {
    try {
        const { room_number, building, floor, capacity, room_type, status } = req.body;
        const [result] = await pool.execute(
            'INSERT INTO classrooms (room_number, building, floor, capacity, room_type, status) VALUES (?, ?, ?, ?, ?, ?)',
            [room_number, building, floor, capacity || 60, room_type || 'Lecture Hall', status || 'Active']
        );
        res.status(201).json({ id: result.insertId });
    } catch (error) {
        res.status(500).json({ error: 'Internal Server Error' });
    }
});

// --- TIME SLOTS API ---
router.get('/timeslots', async (req, res) => {
    try {
        const [rows] = await pool.execute('SELECT * FROM time_slots ORDER BY start_time ASC');
        res.json(rows);
    } catch (error) {
        res.status(500).json({ error: 'Internal Server Error' });
    }
});

router.post('/timeslots', async (req, res) => {
    try {
        const { period_number, start_time, end_time, is_break, title } = req.body;
        const [result] = await pool.execute(
            'INSERT INTO time_slots (period_number, start_time, end_time, is_break, title) VALUES (?, ?, ?, ?, ?)',
            [period_number, start_time, end_time, is_break || false, title]
        );
        res.status(201).json({ id: result.insertId });
    } catch (error) {
        res.status(500).json({ error: 'Internal Server Error' });
    }
});

// --- TIMETABLE API ---
router.get('/master', async (req, res) => {
    try {
        const [rows] = await pool.execute(`
            SELECT tm.*, d.name as dept_name, c.name as course_name, s.name as sem_name, a.name as session_name
            FROM timetable_master tm
            JOIN departments d ON tm.department_id = d.id
            JOIN courses c ON tm.course_id = c.id
            JOIN semesters s ON tm.semester_id = s.id
            JOIN academic_sessions a ON tm.academic_session_id = a.id
            ORDER BY tm.created_at DESC
        `);
        res.json(rows);
    } catch (error) {
        res.status(500).json({ error: 'Internal Server Error' });
    }
});

// Simulated Excel Upload endpoint handling JSON data generated by the frontend (which parses the Excel)
router.post('/upload', async (req, res) => {
    // The frontend will parse the Excel and send an array of rows
    const { department_id, course_id, semester_id, academic_session_id, rows } = req.body;
    
    // In a real application we would use transactions here
    const connection = await pool.getConnection();
    try {
        await connection.beginTransaction();

        // 1. Create a draft timetable_master
        const [masterRes] = await connection.execute(
            'INSERT INTO timetable_master (department_id, course_id, semester_id, academic_session_id, status) VALUES (?, ?, ?, ?, ?)',
            [department_id, course_id, semester_id, academic_session_id, 'Draft']
        );
        const masterId = masterRes.insertId;

        const errors = [];
        let validRows = 0;

        // 2. Validate and Insert Entries
        for (let i = 0; i < rows.length; i++) {
            const row = rows[i];
            const { section_id, day_of_week, time_slot_id, subject_id, faculty_id, room_id } = row;

            // Simple validation: Check if faculty is already busy at this time and day
            const [clashCheck] = await connection.execute(
                `SELECT e.id FROM timetable_entries e 
                 JOIN timetable_master m ON e.timetable_master_id = m.id 
                 WHERE e.faculty_id = ? AND e.day_of_week = ? AND e.time_slot_id = ? AND m.status = 'Published'`,
                [faculty_id, day_of_week, time_slot_id]
            );

            if (clashCheck.length > 0) {
                errors.push({ rowNumber: i + 2, error: 'Faculty Clash: Already assigned to another class during this time slot.' });
                continue;
            }

            // Room clash validation
            const [roomClashCheck] = await connection.execute(
                `SELECT e.id FROM timetable_entries e 
                 JOIN timetable_master m ON e.timetable_master_id = m.id 
                 WHERE e.room_id = ? AND e.day_of_week = ? AND e.time_slot_id = ? AND m.status = 'Published'`,
                [room_id, day_of_week, time_slot_id]
            );

            if (roomClashCheck.length > 0) {
                errors.push({ rowNumber: i + 2, error: 'Room Clash: Classroom already occupied during this time slot.' });
                continue;
            }

            // Insert entry
            await connection.execute(
                'INSERT INTO timetable_entries (timetable_master_id, section_id, day_of_week, time_slot_id, subject_id, faculty_id, room_id) VALUES (?, ?, ?, ?, ?, ?, ?)',
                [masterId, section_id, day_of_week, time_slot_id, subject_id, faculty_id, room_id]
            );
            validRows++;
        }

        if (errors.length > 0) {
            // Rollback if there are validation errors to ensure clean state
            await connection.rollback();
            res.status(400).json({ message: 'Validation failed', errors });
        } else {
            await connection.commit();
            res.status(201).json({ message: 'Timetable imported successfully as Draft', masterId, importedRows: validRows });
        }

    } catch (error) {
        await connection.rollback();
        console.error('Upload error:', error);
        res.status(500).json({ error: 'Internal Server Error' });
    } finally {
        connection.release();
    }
});

router.post('/publish/:id', async (req, res) => {
    const { id } = req.params;
    try {
        await pool.execute('UPDATE timetable_master SET status = ?, published_at = NOW() WHERE id = ?', ['Published', id]);
        res.json({ message: 'Timetable published successfully' });
    } catch (error) {
        res.status(500).json({ error: 'Internal Server Error' });
    }
});

export default router;
